version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: django_app
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - nginx
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context:  ./frontend/snap_booking
      dockerfile: ../../docker/frontend.Dockerfile
    container_name: vue_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: npm run build

  db:
    image: postgres
    container_name: keevo
    environment:
      POSTGRES_PASSWORD: keevo
      POSTGRES_DB: keevo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  postgres_data:
